sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start Creating an image with dockerfile"
  - docker build -t test/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true test/docker-react-app npm run test -- --converage

afeter_success:
  - echo "Test Success"